### ISSUE TITLE
Question on the Hardware Setups

### ISSUE THREAD

**Issue by cs329yangzhong** [Shen-Chenhui/SentBS#2]
Dear Authors, thank you very much for sharing the code. May I ask about the GPU Memory you used to load and test the beam-search-sent model? When I tried to test with another backbone (led-base) and an in-domain classifier with BERT checkpoints, the generation kept giving OOM errors on a 24 GB 3090 Graphic Card. 

I suspect that the problem is attributed to my input being way longer (6000 tokens), and the target sentence length can also be up to 10 cents. Any suggestions on how to improve the inference? (reducing the sentence-by-sentence generating GPU load?)

Thank you!

**Comment by Shen-Chenhui** [comment]
I think you are right. 
One easier way to check is to truncate the input and set max_target_length to be smaller and see whether you may avoid the OOM error. 
If the issue is confirmed and you want the long input and output, maybe it would be better to switch to a larger card.
Another possibility may be to reduce the k value to generate fewer parallel sentences (as seen from my experiments k values from 4-8 all give relatively stable but good results).

Unfortunately, I think fitting long input and generation target on smaller-sized cards is still a challenging research question, you may look for some alternative method to reduce memory usage. LED seems to be a good direction, so sorry to hear that it is still OOM.

**Comment by cs329yangzhong** [comment]
Thanks for the suggestions! Currently, a length of 2048 and a beam size of 2 can work. I will try to explore other combinations.  I read that in your paper, you used a V100 card, and wonder whether it has 16 or 32 GB Memory?

**Comment by Shen-Chenhui** [comment]
Hi, the V100 card that I use has 32G memory.

Wish you all the best!
I will be closing this issue if there are no further questions.

**Comment by cs329yangzhong** [comment]
Thank you very much!
